# Generated by Django 3.2.9 on 2021-12-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
